services:
  db-belajar:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: belajar
      POSTGRES_USER: belajar
      POSTGRES_PASSWORD: docker
    ports:
      - 12345:5432
    volumes:
      - ./db-belajar:/var/lib/postgresql/data
  
  app-belajar:
    image: endymuhardin/belajar-container:latest
    environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://10.99.18.57:12345/belajar
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-belajar:5432/belajar
    ports:
      - 10001:8080