services:
  db-belajar:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: belajar
      POSTGRES_USER: belajar
      POSTGRES_password: docker
    ports:
      - 12345:5432
    volumes:
      - ./db-belajar:/var/lib/postgresql/data