apiVersion: v1
kind: Secret
metadata:
  name: belajar-secret
  labels:
    app: belajar
type: Opaque
stringData:
  # Using stringData for easier readability
  # Kubernetes will automatically base64 encode this value
  POSTGRES_PASSWORD: "docker"
